name: Build Service Environment
trigger: none

parameters:
  - name: branchName
    type: string

pool:
  vmImage: ubuntu-latest

variables:
- group: HELM_VARIABLES
- group: DOCKER_VARIABLES
- group: KUBECTL_VARIABLES

stages:
  - stage: Build
    jobs:
      - job: CalculateNamespace
        steps:
          - bash: |
              echo "##vso[task.setvariable variable=myNameSpace;isoutput=true]$bn | sed -e "s#/#-#g" | sed -e "s#\.#-#g""
            name: cbn
            env:
              bn: ${{ parameters.branchName }}
      - job: BuildServiceEnvironmentWithArgoCD
        displayName: Build Service Environment with ArgoCD
        dependsOn:
          - CalculateNamespace
        variables:
          name-space: $[dependencies.CalculateNamespace.outputs['cbn.myNameSpace']]
        steps: 
          - task: HelmDeploy@0
            inputs:
              kubernetesCluster: 'fsmakkaAKS'
              azureSubscriptionForACR: '$(K8S_SUBS)'
              azureResourceGroupForACR: 'fsm-akka'
              connectionType: Kubernetes Service Connection
              kubernetesServiceConnection: 'fsm_akka_aks'
              azureContainerRegistry: 'fsm_akka_docker_registry'
              chartType: FilePath
              chartPath: 'helm'
              releaseName: 'fsm-akka'
              namespace: $(name-space)
              command: 'upgrade'
              arguments: '--install --create-namespace'
              overrideValues: |
                targetBranch=${{ parameters.branchName }}
