name: Build Service Environment
trigger: none

parameters:
  - name: branchName
    type: string

pool:
  vmImage: ubuntu-latest

variables:
- group: HELM_VARIABLES
- group: DOCKER_VARIABLES
- group: KUBECTL_VARIABLES

stages:
  - stage: Build
    jobs:
      - job: BuildServiceEnvironmentWithArgoCD
        displayName: Build Service Environment with ArgoCD
        steps:
          - task: DownloadSecureFile@1
            name: clientCertificate
            displayName: "Download Client Certificate"
            inputs:
              secureFile: 'K8S_CLIENT_CERTIFICATE.txt'
          - task: DownloadSecureFile@1
            name: clientKey
            displayName: "Download Client Key"
            inputs:
              secureFile: 'K8S_CLIENT_KEY.txt'
          - task: HelmDeploy@0
            inputs:
              kubernetesCluster: 'fsmakkaAKS'
              azureSubscriptionForACR: '$(K8S_SUBS)'
              azureResourceGroupForACR: 'fsm-akka'
              connectionType: Kubernetes Service Connection
              kubernetesServiceConnection: 'fsm_akka_aks'
              azureContainerRegistry: 'fsm_akka_docker_registry'
              chartType: FilePath
              chartPath: 'helm'
              releaseName: 'fsm-akka'
              namespace: ${{ parameters.branchName.replace('/', '-').replace('.', '-') }}
              command: 'upgrade'
              arguments: '--install --create-namespace '
              overrideValues: |
                targetBranch=${{ parameters.branchName }}
