name: Build Service Environment
trigger: none

parameters:
  - name: branchName
    type: string

pool:
  vmImage: ubuntu-latest

variables:
- group: HELM_VARIABLES
- group: DOCKER_VARIABLES

stages:
  - stage: Build
    jobs:
      - job: BuildServiceEnvironmentWithArgoCD
        displayName: Build Service Environment with ArgoCD
        steps:
          - pwsh: |
              $namespace = $env:BRANCH_NAME.replace('/', '-').replace('.', '-')
              Write-Host "Namespace: $namespace"
              helm registry login fsmakka.azurecr.io --username $(HELM_USER) --password $(HELM_PASSWORD)
              Write-Host "Command: helm upgrade --install fsm-akka . -n $namespace --create-namespace --set targetBranch=$env:BRANCH_NAME"
              helm upgrade --install fsm-akka . -n $namespace --create-namespace --set targetBranch=$env:BRANCH_NAME
            displayName: Install ArgoCD Custom Resource Definition
            env:
              BRANCH_NAME: ${{ parameters.branchName }}
