stages:
  - deploy

variables:
  CI_IMAGE_VERSION: v17.36.0

build-service-environment-namespace:
  stage: deploy
  script:
    - |
      export
      set +e
      K8S_NAMESPACE=$(echo $BRANCH_NAME | sed -e "s#/#-#g" | sed -e "s#\.#-#g" | sed -e "s#_#-#g")
      echo "Namespace: $K8S_NAMESPACE"
      K8S_NAMESPACE=$(echo $K8S_NAMESPACE | tr '[:upper:]' '[:lower:]')
      echo "K8S_NAMESPACE=$K8S_NAMESPACE" > build.env
  artifacts:
    reports:
      dotenv: build.env

build-service-environment:
  stage: deploy
  image: "${CI_REGISTRY}/gitlab-com/gl-infra/k8s-workloads/common/k8-helm-ci:${CI_IMAGE_VERSION}"
  needs:
    - job: build-service-environment-namespace
      artifacts: true
  script:
    - |
      echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
      gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
      gcloud container clusters get-credentials fsmakka-gke-dev --zone europe-west3-c --project fsmakka
      cd helm
      ls -al
      echo "helm upgrade --install fsm-akka-4eyes . --create-namespace -n $K8S_NAMESPACE -f values-gke.yaml --set targetBranch=$BRANCH_NAME"
      helm upgrade --install fsm-akka-4eyes . --create-namespace -n $K8S_NAMESPACE -f values-gke.yaml --set targetBranch=$BRANCH_NAME
      rm /tmp/$CI_PIPELINE_ID.json
  rules:
    - if: ($USE_CASE_2 == "true" || $USE_CASE_4 == "true" || $USE_CASE_6 == "true") && $USE_CASE_3 != "true" && $USE_CASE_5 != "true" && $USE_CASE_7 != "true" && $USE_CASE_11 != "true"
      when: always
    - when: never

cleanup-service-environment:
  stage: deploy
  image: "${CI_REGISTRY}/gitlab-com/gl-infra/k8s-workloads/common/k8-helm-ci:${CI_IMAGE_VERSION}"
  needs:
    - job: build-service-environment-namespace
      artifacts: true
  script:
    - |
      export
      echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
      gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
      gcloud container clusters get-credentials fsmakka-gke-dev --zone europe-west3-c --project fsmakka
      cd helm
      echo "helm delete fsm-akka-4eyes -n $K8S_NAMESPACE"
      helm delete fsm-akka-4eyes -n $K8S_NAMESPACE
      kubectl delete namespace $K8S_NAMESPACE
      rm /tmp/$CI_PIPELINE_ID.json
  rules:
    - if: ($USE_CASE_3 == "true" || $USE_CASE_5 == "true" || $USE_CASE_7 == "true" || $USE_CASE_11 == "true")
      when: always
    - when: never
