stages:
  - deploy

variables:
  CI_IMAGE_VERSION: v17.36.0
  K8S_NAMESPACE: ""

build-service-environment-namespace:
  stage: deploy
  script:
    - |
      export
      set +e
      K8S_NAMESPACE=echo $BRANCH_NAME

      echo "Namespace: K8S_NAMESPACE"
      K8S_NAMESPACE=${K8S_NAMESPACE@L}

build-service-environment:
  stage: deploy
  image: "${CI_REGISTRY}/gitlab-com/gl-infra/k8s-workloads/common/k8-helm-ci:${CI_IMAGE_VERSION}"
  needs:
    - job: build-service-environment-namespace
      artifacts: true
  script:
    - |
      echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
      gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
      gcloud container clusters get-credentials fsmakka-gke-dev --zone europe-west3-c --project fsmakka
      cd helm
      ls -al
      echo "helm upgrade --install fsm-akka-4eyes . --create-namespace -n $K8S_NAMESPACE -f values-gke.yaml --set targetBranch=$BRANCH_NAME"
      helm upgrade --install fsm-akka-4eyes . --create-namespace -n $K8S_NAMESPACE -f values-gke.yaml --set targetBranch=$BRANCH_NAME
      rm /tmp/$CI_PIPELINE_ID.json
