apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foureyes
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: {{ .Values.cluster.name }}
    namespace: {{ .Release.Namespace }}
  project: fsm-akka-4eyes-project
  source:
    repoURL: "https://github.com/mehmetsalgar/fsm-akka-dev-environment.git"
    path: {{ .Values.source.path }}
    directory:
      recurse: true
    targetRevision: {{ .Values.targetBranch }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true