name: Create ArgoCD Application for Future Branch Environment
run-name: Create ArgoCD Application for branch ${{ inputs.branch-name }} triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        type: string
        required: true
      day-over:
        type: boolean
        default: false
jobs:
  calculate-namespace:
    runs-on: ubuntu-latest
    outputs:
      namespace: ${{ steps.findandreplace2.outputs.value }}
    steps:
      - id: findandreplace
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ inputs.branch-name }}
          find: '/'
          replace: '-'
          replaceAll: 'true'
      - id: findandreplace1
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ steps.findandreplace.outputs.value }}
          find: '.'
          replace: '-'
          replaceAll: 'true'
      - id: findandreplace2
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ steps.findandreplace1.outputs.value }}
          find: '_'
          replace: '-'
          replaceAll: 'true'
  calculate-helm-command:
    runs-on: ubuntu-latest
    needs: calculate-namespace
    outputs:
      helm-command: ${{ steps.dayOver.outputs.helm_command}}
      cluster-name: ${{ steps.dayOver.outputs.cluster_name}}
    steps:
      - id: dayOver
        shell: bash
        env:
          DAY_OVER: ${{ inputs.day-over }}
        run: |
          if test true -eq $DAY_OVER; then
            #file exists
            echo "helm_command=helm upgrade fsm-akka . --install -n ${{ needs.calculate-namespace.outputs.namespace }} --create-namespace --set targetBranch=${{ inputs.branch-name }} --set cluster.name=fsmakkaGKEDayOver -f values-gke-github.yaml" >> "$GITHUB_OUTPUT"
            echo "cluster_name=fsmakka-gke-dev-day-over" >> "$GITHUB_OUTPUT"
          else
            echo "helm_command=helm upgrade fsm-akka . --install -n ${{ needs.calculate-namespace.outputs.namespace }} --create-namespace --set targetBranch=${{ inputs.branch-name }} -f values-gke-github.yaml" >> "$GITHUB_OUTPUT"
            echo "cluster_name=fsmakka-gke-dev" >> "$GITHUB_OUTPUT"
          fi
  call-build-environment-for-branch:
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: calculate-helm-command
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/helm-install.yaml@master
    with:
      helm-command: "${{ needs.calculate-helm-command.outputs.helm-command }}"
      cluster-name: "${{ needs.calculate-helm-command.outputs.cluster-name }}"
    secrets: inherit
