name: Create ArgoCD Application for Future Branch Environment
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        type: string
jobs:
  calculate-branch-name:
    outputs:
      branchName: ${{ teps.findandreplace.outputs.value }}
    steps:
      - id: findandreplace
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ inputs.branch-name }}
          find: '/'
          replace: '-'
  call-build-environment-for-future-branch:
    needs: calculate-branch-name
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/helm-install.yaml@master
    with:
      branch-name: ${{ inputs.branch-name }}
      helm-command: helm upgrade --install fsm-akka . -n ${{ needs.calculate-branch-name.branchName }} --create-namespace
